version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8021}:${BACKEND_PORT:-8021}"
    volumes:
      - ./backend:/app
      - ./proto:/proto
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    tty: true
    ports:
      - "${FRONTEND_PORT:-3021}:${FRONTEND_PORT:-3021}"
    volumes:
      - ./frontend:/app
      - ./proto:/proto
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
  postgres:
    image: postgres:16
    ports: 
      - "${POSTGRES_PORT:-5421}:${POSTGRES_PORT:-5421}"
    environment:
      POSTGRES_PORT: "${POSTGRES_PORT:-5421}"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "simple_drive"
    command: -p ${POSTGRES_PORT:-5421}
    volumes:
      - .postgres_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    env_file:
      - .env
    command: server --console-address ":${MINIO_WEB_PORT:-9013}" /data
    ports:
      - "${MINIO_PORT:-9012}:${MINIO_PORT:-9012}"
      - "${MINIO_WEB_PORT:-9013}:${MINIO_WEB_PORT:-9013}"
    volumes:
      - ./.minio/data:/data
      - ./.minio/config:/root/.minio
  createbuckets:
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc policy download myminio/images;
      exit 0;
      "
