version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-3021}:${BACKEND_PORT:-3021}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-8021}:${FRONTEND_PORT:-8021}"
    command: sh -c "npm run dev"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    env_file:
      - .env
  postgres:
    image: postgres:16
    ports: 
      - "${POSTGRES_PORT:-5421}:${POSTGRES_PORT:-5421}"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":${MINIO_WEB_PORT:-9013}" /data
    ports:
      - "${MINIO_PORT:-9012}:${MINIO_PORT:-9012}"
      - "${MINIO_WEB_PORT:-9013}:${MINIO_WEB_PORT:-9013}"
