version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-3021}:${BACKEND_PORT:-3021}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-8021}:${FRONTEND_PORT:-8021}"
    command: sh -c "npm run dev"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    env_file:
      - .env
