version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8021:8021"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "3021:3021"
    command: sh -c "npm run dev"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
